const jsonString = """
[
  {
    "name": "Albedo",
    "vision": "Geo",
    "weapon": "Sword",
    "nation": "Mondstadt",
    "affiliation": "Knights of Favonius",
    "rarity": 5,
    "constellation": "Princeps Cretaceus",
    "birthday": "0000-09-13",
    "description": "A genius known as the Kreideprinz, he is the Chief Alchemist and Captain of the Investigation Team of the Knights of Favonius.",
    "skillTalents": [
      {
        "name": "Favonius Bladework - Weiss",
        "unlock": "Normal Attack",
        "description": "Normal Attack. Perform up to 5 rapid strikes. Charged Attack. Consumes a certain amount of Stamina to unleash 2 rapid sword strikes. Plunging Attack. Plunges from mid-air to strike the ground below, damaging opponents along the path and dealing AoE DMG upon impact.",
        "type": "NORMAL_ATTACK"
      },
      {
        "name": "Abiogenesis: Solar Isotoma",
        "unlock": "Elemental Skill",
        "description": "Albedo creates a Solar Isotoma using alchemy, which deals AoE Geo DMG on appearance.Solar Isotoma. When enemies within the Solar Isotoma zone are hit, the Solar Isotoma will generate Transient Blossoms which deal AoE Geo DMG. DMG dealt scales off Albedo's DEF. Transient Blossoms can only be generated once every 2s. When a character is located at the locus of the Solar Isotoma, the Solar Isotoma will accumulate Geo power to form a crystallized platform that lifts the character up to a certain height. Only one crystallized platform can exist at a time. Solar Isotoma is considered a Geo construct. Hold to designate the location of the skill.",
        "type": "ELEMENTAL_SKILL"
      },
      {
        "name": "Rite of Progeniture: Tectonic Tide",
        "unlock": "Elemental Burst",
        "description": "Under Albedo's command, Geo crystals surge and burst forth, dealing AoE Geo DMG in front of him. If a Solar Isotoma created by Albedo himself is on the field, 7 Fatal Blossoms will be generated in the Solar Isotoma field, bursting violently into bloom and dealing AoE Geo DMG. Tecotonic Tide DMG and Fatal Blossom DMG will not generate Transient Blossoms.",
        "type": "ELEMENTAL_BURST"
      }
    ],
    "passiveTalents": [
      {
        "name": "Calcite Might",
        "unlock": "Unlocked at Ascension 1",
        "description": "Transient Blossoms generated by Abiogenesis: Solar Isotoma deal 25% more DMG to enemies whose HP is below 50%.",
        "level": 1
      },
      {
        "name": "Homuncular Nature",
        "unlock": "Unlocked at Ascension 4",
        "description": "Using Rite of Progeniture: Tectonic Tide increases the Elemental Mastery of nearby party members by 125 for 10s.",
        "level": 4
      },
      {
        "name": "Flash of Genius",
        "unlock": "Unlocked Automatically",
        "description": "When Albedo crafts Weapon Ascension Materials, he has a 10% chance to receive double the product.",
        "level": 1
      }
    ],
    "constellations": [
      {
        "name": "Flower of Eden",
        "unlock": "Constellation Lv. 1",
        "description": "Transient Blossoms generated by Albedo's Abiogenesis: Solar Isotoma regenerate 1.2 Energy for Albedo.",
        "level": 1
      },
      {
        "name": "Opening of Phanerozoic",
        "unlock": "Constellation Lv. 2",
        "description": "Transient Blossoms generated by Abiogenesis: Solar Isotoma grant Albedo Fatal Reckoning for 30s: Each stack of Fatal Reckoning increases DMG by of Albedo's DEF. The effect stacks up to 4 times. Unleashing Rite of Progeniture: Tectonic Tide consumes all stacks of Fatal Reckoning, increasing the DMG dealt by the Tectonic Tide and Fatal Blossoms based on the number of stacks consumed.",
        "level": 2
      },
      {
        "name": "Grace of Helios",
        "unlock": "Constellation Lv. 3",
        "description": "Increases the level of Abiogenesis: Solar Isotoma by 3. Maximum upgrade level is 15.",
        "level": 3
      },
      {
        "name": "Descent of Divinity",
        "unlock": "Constellation Lv. 4",
        "description": "Solar Isotoma increases Plunging Attack DMG by 30% for active party members within the AoE.",
        "level": 4
      },
      {
        "name": "Tide of Hadaen",
        "unlock": "Constellation Lv. 5",
        "description": "Increases the level of Rite of Progeniture: Tectonic Tide by 3. Maximum upgrade level is 15.",
        "level": 5
      },
      {
        "name": "Dust of Purification",
        "unlock": "Constellation Lv. 6",
        "description": "If active party members within the AoE are protected by a shield created by Crystallize, Solar Isotoma increases their DMG by 17%.",
        "level": 6
      }
    ],
    "vision_key": "GEO",
    "weapon_type": "SWORD"
  }
]""";